#ifndef GENTYPES_H_INCLUDED
#define GENTYPES_H_INCLUDED

enum PHONETIC_FUNCTION {EMPTY = 'e', V = 'v', I = 'i', R = 'r', D = 'd'};
enum GENSITU {START, ENDPOSTV, MIDPOSTV, MIDPOSTDV, MIDPOSTR};
enum SUBPHONF {VU, VB, ISG, ILP, IDS, INS, ITS, ISS, DSG, DSS, DTS, DHP, 
	RSG, RKS, RRS, RMS, RPS, RNS, RLS, RSP};
#endif // GENTYPES_H_INCLUDED